const banks = ["AXIS BANK",
  "CATHOLIC SYRIAN BANK",
  "CITY UNION BANK",
  "EQUITAS SMALL FINANCE BANK LTD",
  "FINCARE SMALL FINANCE BANK",
  "IDFC FIRST BHARAT BANK",
  "INDIAN BANK",
  "INDUSIND BANK",
  "KARUR VYSYA BANK",
  "PUNJAB NATIONAL BANK",
  "SOUTH INDIAN BANK",
  "STATE BANK OF INDIA",
  "UCO BANK",
  "UJJIVAN SMALL FINANCE BANK",
  "UNITY SMALL FINANCE BANK"];
const financialInstitutions = ["AADHAR HOUSING FINANCE LTD",
  "AHAM HOUSING FINANCE LTD",
  "AMBIT HOUSING FINANCE LTD",
  "WONDER HOME FINANCE",
  "ANNAPURNA FINANCIAL PVT LTD",
  "ARKA FINCAP LIMITED",
  "ASHOK LEYLAND FINANCE LTD",
  "AVANSE FINANCIAL SERVICE",
  "BAJAJ HOUSING FINANCE LTD",
  "CATALYST FINANCIAL LTD",
  "CHOLAMANDALAM HOME FINANCE LTD",
  "FEDBANK FINANCIAL SERVICE LTD",
  "GODREJ CAPITAL LTD",
  "HDB FINANCIAL SERVICE",
  "HINDUJA HOUSING FINANCE LTD",
  "ICICI HOME FINANCE LTD",
  "INCRED FINANCIAL SERVICE",
  "INDOSTAR HOME FINANCE LTD",
  "JM FINANCE",
  "JIO FINANCE LTD",
  "L&T FINANCE LTD",
  "MAHINDRA HOME FINANCE LTD",
  "MANAPURAM HOME FINANCE",
  "MOTILAL OSWAL HOME FINANCE LTD",
  "MUTHOOT HOME FINANCE LTD",
  "NIDO HOME FINANCE LTD",
  "PIRAMAL CAPITAL & HOUSING FINANCE LTD",
  "PNB HOUSING FINANCE LTD",
  "PRAYAAN CAPITAL PVT LTD",
  "PROFECTUS CAPITAL PVT LTD",
  "REAL TOUCH HOME FINANCIAL LTD",
  "SMFG HOME FINANCE CO LTD",
  "SUNDARAM HOME FINANCE LTD",
  "TRUHOME FINANCE LIMITED",
  "UGRO CAPITAL FINANCE LTD",
  "VERITAS HOUSING FINANCIAL LTD",
  "VISTAAR FINANCIAL SERVICE"];

function renderList(data, containerId) {
  const container = document.getElementById(containerId);
  container.innerHTML = "";

  data.forEach(name => {
    const item = document.createElement("div");
    item.className = "empanelment-card";
    item.textContent = name;
    container.appendChild(item);
  });
}

document.addEventListener("DOMContentLoaded", () => {
  renderList(banks, "banks-grid");
  renderList(financialInstitutions, "financial-grid");
});
